name: CI
on:
  push:
    branches: ['master']
    tags: ['*']
  pull_request:
    branches: ['master']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
      - run: npm ci
      - run: npm run lint
      - run: npm test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-typegen:
    name: Publish openapi-client-axios-ts-gen
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: .
      - run: npm ci
        working-directory: typegen
      - run: npm publish || true
        working-directory: typegen
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
